apiVersion: apps/v1
kind: Deployment
metadata:
  name: payments-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: payments-app
  template:
    metadata:
      labels:
        app: payments-app
    spec:
      containers:
      - name: payments-app
        image: payments:0.0.1
        ports:
        - containerPort: 5000
        env:
        - name: MONGO_URI
          value: mongodb://mongo-service.default.svc.cluster.local:27017/
        - name: REDIS_HOST
          value: redis-service.default.svc.cluster.local
        resources:
          limits:
            cpu: 100m
            memory: 100Mi
---
apiVersion: v1
kind: Service
metadata:
  name: payments-app-service
spec:
  selector:
    app: payments-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
  type: ClusterIP